#!/bin/bash

[ -e readme.md ] && rm readme.md
cd final
for i in *png; do
  title=`head -1 ../src/${i/png/txt}`
  author=`head -2 ../src/${i/png/txt} | tail -1`

  echo -e "\n**$title** by $author " >> ../readme.md
  echo "<img border=\"1\" src=https://raw.githubusercontent.com/kristopolous/qr-project/master/final/$i>" >> ../readme.md
done
