#!/bin/bash

qrgen() {
  echo -e "\nQR code generation"
  for i in src/*txt; do
    fname=`basename $i`
    dest=${fname/txt/png}
    if [ -e dest/$dest -a -z "$FORCE" ]; then
      echo "   $dest exists"
    else
      echo " * $dest"
      cat $i | qrencode -lQ -ic --output=dest/$dest
    fi
  done
}

label() {
  echo -e "\nLabeling"
  for  i in dest/*png; do
    fname=`basename $i`
    if [ -e final/$fname -a -z "$FORCE" ]; then
      echo "   $fname already generated"
    else
      name=`./gen-name`
      echo " * $name = $fname"
      convert $i -filter box -resize 2048x -gravity south -font DejaVu-Sans-Mono -pointsize 60 -annotate 0x0 "$name" final/$fname
    fi
  done
}

qrgen
label

./gen-readme
