#!/bin/bash

qrgen() {
  echo -e "\nQR code generation"
  for i in src/*txt; do
    fname=`basename $i`
    dest=${fname/txt/png}
    if [ -e dest/$dest -a -z "$FORCE" ]; then
      echo "   $dest exists"
    else
      echo " * $dest"
      cat $i | qrencode -m 1 -d 150 -lH -ic --output=dest/$dest
    fi
  done
}

label() {
  echo -e "\nLabeling"
  num=0
  count=`ls dest/*png | wc -l`
  incr=$(( 360 / $count ))
  perc=0
  for  i in dest/*png; do
    (( num ++ ))
    fname=`basename $i`
    if [ -e final/$fname -a -z "$FORCE" ]; then
      echo "   $fname"
    else
      name=`./gen-name`
      code=`printf "A.%02d" $num`
      echo " * $name = $fname"
      convert $i -filter box -resize 3072x -extent 3072x3272 -gravity south -font DejaVu-Sans-Mono-Bold -pointsize 70 -annotate 0x0 "$name" \
        -gravity southwest -font DejaVu-Sans-Mono-Bold -pointsize 30 -fill "#777" -annotate 0x0 "** $code" \
        +level-colors "hsl($perc%, 80%, 15%)", final/$fname
    fi
    perc=$(( $perc + $incr ))
  done
}

qrgen
label

./gen-readme
