#!/bin/bash
. ../tools/common.sh

generate() {
  cd html
  count=0
  for i in *html; do
    pdf=${i/html/pdf}
    status $count $pdf

    ../wkhtmltopdf \
      -T 0 -B 0 -R 0 -L 0 \
      -d 300 --minimum-font-size 9 \
      --print-media-type -s Letter \
      $i ../output/$pdf >& /dev/null

    (( count++ ))
  done
  cd ..
}

build() {
  ext=$2
  what=$1
  page=0
  row=0
  col=0
  fname=''

  cd html
  for i in ../../$what/output/*.$ext; do
    if [ $row -eq 0 ]; then 
      if [ $col -eq 0 ]; then
        if [ "$fname" != "" ]; then
          echo "</div>" >> $fname
        fi
        fname=$what-$page.html
        cp ../header.html $fname
        echo "<script>var base='$what';</script>" >> $fname
      fi
      echo "<span id='col$col'>" >> $fname
    fi

    echo "<div><img src='$i'></div>" >> $fname
    (( row ++ ))
    if [ $row -eq 3 ]; then
      echo "</span>" >> $fname
      (( col ++ ))
      row=0
    fi

    if [ $col -eq 2 ]; then
      break
      (( page++ ))
      col=0
    fi

    #echo "$fname $col $row"
  done
  echo "</div>" >> $fname
  cd ..
}

build prompt png
build art jpg

#generate
convert output/prompt-0.pdf -resize 1160x prompt-0.png
