#!/bin/bash

base=Hello_my_name_is_sticker.png
font=Nimbus-Sans-L-Bold

labelgen() {
  num=0
  count=`cat prompts.txt | wc -l`
  incr=$(( 360 / $count ))
  perc=0

  while read -r line
  do
    (( num ++ ))
    fname=$num.png
    echo $ix $line
    convert $base -fill white -font $font \
      -gravity north -pointsize 360 -annotate +0+40 "HELLO" \
      -gravity north -pointsize 200 -annotate +0+450 "$line" \
      -fill 'rgba(255,255,255,0.7)' -font Nimbus-Sans-L -gravity southwest -pointsize 35 -annotate +80+60 "projectpoetryla.org" \
      +level-colors "hsl($perc%, 70%, 15%)", output/$fname
    perc=$(( $perc + $incr ))
  done < prompts.txt
}

[ -e $base ] || convert Hello_my_name_is_sticker.svg -filter -resize 3072x $base

labelgen

