#!/usr/bin/python3
# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
from glob import glob
from shutil import copyfile
from subprocess import call
import re
import os
import sys

FNULL = open(os.devnull, 'w')
fcount = 0

if not os.path.isdir('html'):
  os.mkdir('html') 

if not os.path.isdir('output'):
  os.mkdir('output') 

def poem(title, author, body):
  html.write("<h1>{0}</h1>".format(title))
  html.write("<h2>{0}</h2>".format(author))

  columns = 1
  if count > 12:
    columns = 2
    cutoff = round(count / 2)
    html.write('<span class="first">')

  newp = True
  line_num = 0

  for row in lines[3:]:
    row = row.strip()

    if line_num == cutoff:
      if not newp:
       html.write('</p>')
      html.write('</span><span>')
      newp = True

    if newp:
      html.write("<p>"); 
      newp = False
    elif len(row) > 0:
      html.write("<br>")

    if len(row) == 0:
      html.write("</p>")
      newp = True
    else:
      html.write(row)

    line_num += 1

  html.write("</p>")
  if cutoff:
    html.write('</span>')
  html.close()

def emit(what, number):
  print(number, what)

"""
def hard_parse():
    with open(fname) as f:
      blank_count = 0
      title = None
      author = None
      poem_lines = []
      last_poem = {}
      start_parse = False
      longest_line = 0
      max_blank = 0
      line = line_raw.strip() 

      if line == '*       *       *       *       *':
        start_parse = True
        continue

      if not start_parse:
        continue

      if len(line) == 0:
        blank_count += 1
        if len(poem_lines) > 0 and blank_count < 2 and max_blank < 3:
          poem_lines.append(line)
        max_blank = max(max_blank, blank_count)
        continue
      
      has_lcase = re.search('[a-z]', line)
      if has_lcase is None:
        if title is None:
          title = line
        elif len(poem_lines) > 0 and author is None:
          author = line
          continue

      #print(has_lcase, blank_count, line)
      if has_lcase and blank_count == 2:
        last_poem['body'] = poem_lines
        last_poem['width'] = longest_line
        last_poem['author'] = author
        last_poem['height'] = len(poem_lines)
        emit(last_poem)

        last_poem['title'] = title
        poem_lines = [line]
        longest_line = 0
        max_blank = 0
        title = None
        author = None

      elif len(poem_lines) > 0 and max_blank < 3:
        poem_lines.append(line)
     
      longest_line = max(longest_line, len(line))
      max_blank = max(max_blank, blank_count)
      blank_count = 0
"""

for fname in glob('txt/*.txt'):
  print(" * %s %s" % (str(fcount),fname))
  """
  fcount = fcount+1
  html_name = "html{0}html".format(fname[3:-3])
  copyfile("header.html", html_name)
  html = open(html_name, "a")
  """
  with open(fname) as f:
    blank_count = 0
    title = None
    author = None
    poem_lines = []
    last_poem = {}
    start_parse = False
    longest_line = 0
    max_blank = 0
    poem_count = 0

    for line_raw in f.readlines():
      line = line_raw.strip() 
      has_lcase = re.search('[a-z]', line)
      is_new = re.search('\*     ', line)

      if is_new:
        start_parse = True

        if len(poem_lines):
          if len(poem_lines[-1]) == 0:
            poem_lines = poem_lines[:-1]

          last_poem['body'] = poem_lines
          last_poem['width'] = longest_line

          if author and author[-1] == '.':
            author = author[:-1]

          last_poem['author'] = author
          last_poem['height'] = len(poem_lines)
          poem_count += 1
          emit(last_poem, poem_count)

        poem_lines = []
        title = None
        author = None

        longest_line = 0
        max_blank = 0
        blank_count = 0

        continue

      if not start_parse:
        continue

      print(has_lcase, blank_count, line)

      if len(line) == 0:
        blank_count += 1
        if len(poem_lines) > 0 and not author:
          poem_lines.append(line)
        continue
      
      if has_lcase is None:
        if title is None:
          title = line
        elif len(poem_lines) > 0 and author is None:
          author = line
          continue

      #print(has_lcase, blank_count, line)
      if has_lcase and blank_count == 2:
        if title and title[-1] == '.':
          title = title[:-1]
        last_poem['title'] = title
        poem_lines.append(line)

      elif len(poem_lines) > 0:
        poem_lines.append(line)
     
      longest_line = max(longest_line, len(line))
      max_blank = max(max_blank, blank_count)
      blank_count = 0



    """
    title = lines[0].strip()
    author = lines[1].strip()

    count = len(lines) - 3
    cutoff = False
    """


  #png_name = "output{0}png".format(fname[3:-3])
  #call(['/usr/bin/wkhtmltoimage', '--width', '3072', html_name, png_name], stdout=FNULL, stderr=FNULL)
  #call(['/usr/bin/convert', png_name, '-trim', png_name])
    
