#!/bin/bash

qrgen() {
  echo -e "\nQR code generation"
  for i in src/*txt; do
    fname=`basename $i`
    dest=${fname/txt/png}
    if [ -e dest/$dest -a -z "$FORCE" ]; then
      echo "   $dest exists"
    else
      echo " * $dest"
      cat $i | qrencode -m 3 -d 300 -lH -i --output=dest/$dest
    fi
  done
}

label() {
  echo -e "\nLabeling"
  num=0
  count=`ls dest/*png | wc -l`
  incr=$(( 360 / $count ))
  perc=0

  for i in dest/*png; do
    (( num ++ ))
    code=`printf "A.%02d" $num`
    fname=$code-`basename $i`
    fname=`basename $i`
    if [ -e final/$fname -a -z "$FORCE" ]; then
      echo "   $fname"
    else
      name=`./gen-name`
      echo " * $name = $fname"
      convert $i -filter box -resize 3072x -extent 3072x3172 -font DejaVu-Sans-Mono-Bold \
        -gravity south -pointsize 70 -annotate +0+20 "$name" \
        +level-colors "hsl($perc%, 70%, 15%)", \
        -gravity southwest -pointsize 45 -fill "#222" -annotate 0x0 "** $code" \
        -rotate 90 final/$fname
    fi
    perc=$(( $perc + $incr ))
  done
}

qrgen
label

./gen-readme
